outfile:main.o count.o getdata.o ins.o file_r_p.o print.o sorting.o revdata.o
	cc main.o count.o getdata.o ins.o file_r_p.o print.o sorting.o revdata.o -o outfile
main.o:main.c
	cc -c main.c
count.o:count.c
	cc -c count.c
getdata.o:getdata.c
	cc -c getdata.c
ins.o:ins.c
	cc -c ins.c
file_r_p.o:file_r_p.c
	cc -c file_r_p.c
print.o:print.c
	cc -c print.c
sorting.o:sorting.c
	cc -c sorting.c	
revdata.o:revdata.c
	cc -c revdata.c

